spring.application.name=ItemService
server.port=8072

eureka.client.service-url.defaultZone=http://138.2.144.234:8761/eureka

spring.datasource.url=${ITEM_SERVICE_SPRING_DATASOURCE_URL}
spring.datasource.username=${ITEM_SERVICE_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${ITEM_SERVICE_SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123