eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

spring.application.name=apigateway
server.port=8765

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.server.webmvc=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

# Discovery Client Configuration
spring.cloud.gateway.server.webmvc.discovery.locator.enabled=true
spring.cloud.gateway.server.webmvc.discovery.locator.lower-case-service-id=true

# Manual routing configured below - using the loadbalancer for scalable architecture
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/users/**


