eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.application.name=searchService
spring.elasticsearch.uris=http://elasticsearch:9200

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Tracing Configuration
management.tracing.enabled=true
management.observations.http.server.requests.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]


