server.port=8081
spring.application.name=user-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Configuration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

#JWT Config
jwt.secret=f93hF92jf02jf9Jf02jf9Jf02jf9Jf02jf9Jf02jf9Jf02jf9Jf02jf9Jf0
jwt.expiration=86400000

#Rabbit MQ
rabbitmq.exchange: notification.exchange
rabbitmq.routing-key: user.registered

