services:
  discovery-server:
    build:
      context: .
      dockerfile: DiscoveryServer/Dockerfile
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8765:8765"
    depends_on:
      - discovery-server

  search-service:
    build:
      context: .
      dockerfile: SearchService/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server

  notification-service:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server

  event-service:
    build:
      context: .
      dockerfile: EventService/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server

  borrow-service:
    build:
      context: .
      dockerfile: borrowservice/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - discovery-server
